name: Smoke Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  build_ios:
    type: build
    params:
      platform: ios
      profile: preview
  maestro_android:
    type: maestro
    needs: build_android
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path: .maestro/FavoritePodcast.yaml
  maestro_ios:
    type: maestro
    needs: build_ios
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path: .maestro/FavoritePodcast.yaml
